from __future__ import annotations

from project.research.validation.evidence_bundle import PromotionPolicy


def _build_bundle_policy(
    *,
    promotion_profile: str,
    max_q_value: float,
    min_events: int,
    min_stability_score: float,
    min_sign_consistency: float,
    min_cost_survival_ratio: float,
    max_negative_control_pass_rate: float,
    min_tob_coverage: float,
    require_hypothesis_audit: bool,
    allow_missing_negative_controls: bool,
    require_multiplicity_diagnostics: bool,
    require_retail_viability: bool,
    require_low_capital_viability: bool,
    enforce_baseline_beats_complexity: bool,
    enforce_placebo_controls: bool,
    enforce_timeframe_consensus: bool,
    enforce_regime_stability: bool = True,
    require_scope_level_multiplicity: bool = True,
    allow_multiplicity_scope_degraded: bool = True,
    use_effective_q_value: bool = True,
    policy_version: str = "phase4_pr5_v1",
    bundle_version: str = "phase4_bundle_v1",
) -> PromotionPolicy:
    return PromotionPolicy(
        promotion_profile=str(promotion_profile),
        max_q_value=float(max_q_value),
        min_events=int(min_events),
        min_stability_score=float(min_stability_score),
        min_sign_consistency=float(min_sign_consistency),
        min_cost_survival_ratio=float(min_cost_survival_ratio),
        max_negative_control_pass_rate=float(max_negative_control_pass_rate),
        min_tob_coverage=float(min_tob_coverage),
        require_hypothesis_audit=bool(require_hypothesis_audit),
        allow_missing_negative_controls=bool(allow_missing_negative_controls),
        require_multiplicity_diagnostics=bool(require_multiplicity_diagnostics),
        require_retail_viability=bool(require_retail_viability),
        require_low_capital_viability=bool(require_low_capital_viability),
        enforce_baseline_beats_complexity=bool(enforce_baseline_beats_complexity),
        enforce_placebo_controls=bool(enforce_placebo_controls),
        enforce_timeframe_consensus=bool(enforce_timeframe_consensus),
        enforce_regime_stability=bool(enforce_regime_stability),
        require_scope_level_multiplicity=bool(require_scope_level_multiplicity),
        allow_multiplicity_scope_degraded=bool(allow_multiplicity_scope_degraded),
        use_effective_q_value=bool(use_effective_q_value),
        policy_version=str(policy_version),
        bundle_version=str(bundle_version),
    )
