from __future__ import annotations

from ..factory import ScenarioSpec

FUNDING_SCENARIOS = {
    "FUNDING_EXTREME_ONSET_positive": ScenarioSpec(
        name="FUNDING_EXTREME_ONSET_positive",
        event_type="FUNDING_EXTREME_ONSET",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.5},
        expected_events={"FUNDING_EXTREME_ONSET": True},
        excluded_events={},
        tags=["funding", "extreme"],
        difficulty="medium",
    ),
    "FUNDING_EXTREME_ONSET_negative": ScenarioSpec(
        name="FUNDING_EXTREME_ONSET_negative",
        event_type="FUNDING_EXTREME_ONSET",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 0.5},
        expected_events={"FUNDING_EXTREME_ONSET": False},
        excluded_events={},
        tags=["funding", "extreme"],
        difficulty="easy",
    ),
    "FUNDING_PERSISTENCE_TRIGGER_positive": ScenarioSpec(
        name="FUNDING_PERSISTENCE_TRIGGER_positive",
        event_type="FUNDING_PERSISTENCE_TRIGGER",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.0},
        expected_events={"FUNDING_PERSISTENCE_TRIGGER": True},
        excluded_events={},
        tags=["funding", "persistence"],
        difficulty="medium",
    ),
    "FUNDING_PERSISTENCE_TRIGGER_negative": ScenarioSpec(
        name="FUNDING_PERSISTENCE_TRIGGER_negative",
        event_type="FUNDING_PERSISTENCE_TRIGGER",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"FUNDING_PERSISTENCE_TRIGGER": False},
        excluded_events={},
        tags=["funding", "persistence"],
        difficulty="easy",
    ),
    "FUNDING_NORMALIZATION_TRIGGER_positive": ScenarioSpec(
        name="FUNDING_NORMALIZATION_TRIGGER_positive",
        event_type="FUNDING_NORMALIZATION_TRIGGER",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.5},
        expected_events={"FUNDING_NORMALIZATION_TRIGGER": True},
        excluded_events={},
        tags=["funding", "normalization"],
        difficulty="medium",
    ),
    "FUNDING_NORMALIZATION_TRIGGER_negative": ScenarioSpec(
        name="FUNDING_NORMALIZATION_TRIGGER_negative",
        event_type="FUNDING_NORMALIZATION_TRIGGER",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.0},
        expected_events={"FUNDING_NORMALIZATION_TRIGGER": False},
        excluded_events={},
        tags=["funding", "normalization"],
        difficulty="easy",
    ),
    "FUNDING_FLIP_positive": ScenarioSpec(
        name="FUNDING_FLIP_positive",
        event_type="FUNDING_FLIP",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "down", "magnitude_pct": 3.0},
        expected_events={"FUNDING_FLIP": True},
        excluded_events={},
        tags=["funding", "flip"],
        difficulty="hard",
    ),
    "FUNDING_FLIP_negative": ScenarioSpec(
        name="FUNDING_FLIP_negative",
        event_type="FUNDING_FLIP",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.0},
        expected_events={"FUNDING_FLIP": False},
        excluded_events={},
        tags=["funding", "flip"],
        difficulty="easy",
    ),
}

__all__ = ["FUNDING_SCENARIOS"]
