from __future__ import annotations

from ..factory import ScenarioSpec

REGIME_SCENARIOS = {
    "VOL_REGIME_SHIFT_EVENT_positive": ScenarioSpec(
        name="VOL_REGIME_SHIFT_EVENT_positive",
        event_type="VOL_REGIME_SHIFT_EVENT",
        polarity="positive",
        generator_type="context",
        injection_method="inject_vol_regime_shift",
        injection_params={"target_regime": "high"},
        expected_events={"VOL_REGIME_SHIFT_EVENT": True},
        excluded_events={},
        tags=["regime", "volatility"],
        difficulty="medium",
    ),
    "VOL_REGIME_SHIFT_EVENT_negative": ScenarioSpec(
        name="VOL_REGIME_SHIFT_EVENT_negative",
        event_type="VOL_REGIME_SHIFT_EVENT",
        polarity="negative",
        generator_type="context",
        injection_method="inject_vol_regime_shift",
        injection_params={"target_regime": "mid"},
        expected_events={"VOL_REGIME_SHIFT_EVENT": False},
        excluded_events={},
        tags=["regime", "volatility"],
        difficulty="easy",
    ),
    "TREND_TO_CHOP_SHIFT_positive": ScenarioSpec(
        name="TREND_TO_CHOP_SHIFT_positive",
        event_type="TREND_TO_CHOP_SHIFT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 2.0},
        expected_events={"TREND_TO_CHOP_SHIFT": True},
        excluded_events={},
        tags=["regime", "chop"],
        difficulty="medium",
    ),
    "TREND_TO_CHOP_SHIFT_negative": ScenarioSpec(
        name="TREND_TO_CHOP_SHIFT_negative",
        event_type="TREND_TO_CHOP_SHIFT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 3.0},
        expected_events={"TREND_TO_CHOP_SHIFT": False},
        excluded_events={},
        tags=["regime", "chop"],
        difficulty="easy",
    ),
    "CHOP_TO_TREND_SHIFT_positive": ScenarioSpec(
        name="CHOP_TO_TREND_SHIFT_positive",
        event_type="CHOP_TO_TREND_SHIFT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 3.5},
        expected_events={"CHOP_TO_TREND_SHIFT": True},
        excluded_events={},
        tags=["regime", "trend"],
        difficulty="medium",
    ),
    "CHOP_TO_TREND_SHIFT_negative": ScenarioSpec(
        name="CHOP_TO_TREND_SHIFT_negative",
        event_type="CHOP_TO_TREND_SHIFT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"CHOP_TO_TREND_SHIFT": False},
        excluded_events={},
        tags=["regime", "trend"],
        difficulty="easy",
    ),
    "CORRELATION_BREAKDOWN_EVENT_positive": ScenarioSpec(
        name="CORRELATION_BREAKDOWN_EVENT_positive",
        event_type="CORRELATION_BREAKDOWN_EVENT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "down", "magnitude_pct": 3.0},
        expected_events={"CORRELATION_BREAKDOWN_EVENT": True},
        excluded_events={},
        tags=["regime", "correlation"],
        difficulty="hard",
    ),
    "CORRELATION_BREAKDOWN_EVENT_negative": ScenarioSpec(
        name="CORRELATION_BREAKDOWN_EVENT_negative",
        event_type="CORRELATION_BREAKDOWN_EVENT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"CORRELATION_BREAKDOWN_EVENT": False},
        excluded_events={},
        tags=["regime", "correlation"],
        difficulty="easy",
    ),
    "BETA_SPIKE_EVENT_positive": ScenarioSpec(
        name="BETA_SPIKE_EVENT_positive",
        event_type="BETA_SPIKE_EVENT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 5.0},
        expected_events={"BETA_SPIKE_EVENT": True},
        excluded_events={},
        tags=["regime", "beta"],
        difficulty="medium",
    ),
    "BETA_SPIKE_EVENT_negative": ScenarioSpec(
        name="BETA_SPIKE_EVENT_negative",
        event_type="BETA_SPIKE_EVENT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.0},
        expected_events={"BETA_SPIKE_EVENT": False},
        excluded_events={},
        tags=["regime", "beta"],
        difficulty="easy",
    ),
}

__all__ = ["REGIME_SCENARIOS"]
