from __future__ import annotations

from ..factory import ScenarioSpec

TREND_SCENARIOS = {
    "TREND_ACCELERATION_positive": ScenarioSpec(
        name="TREND_ACCELERATION_positive",
        event_type="TREND_ACCELERATION",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 4.0},
        expected_events={"TREND_ACCELERATION": True},
        excluded_events={},
        tags=["trend", "acceleration"],
        difficulty="medium",
    ),
    "TREND_ACCELERATION_negative": ScenarioSpec(
        name="TREND_ACCELERATION_negative",
        event_type="TREND_ACCELERATION",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"TREND_ACCELERATION": False},
        excluded_events={},
        tags=["trend", "acceleration"],
        difficulty="easy",
    ),
    "TREND_DECELERATION_positive": ScenarioSpec(
        name="TREND_DECELERATION_positive",
        event_type="TREND_DECELERATION",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.5},
        expected_events={"TREND_DECELERATION": True},
        excluded_events={},
        tags=["trend", "deceleration"],
        difficulty="medium",
    ),
    "TREND_DECELERATION_negative": ScenarioSpec(
        name="TREND_DECELERATION_negative",
        event_type="TREND_DECELERATION",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 3.0},
        expected_events={"TREND_DECELERATION": False},
        excluded_events={},
        tags=["trend", "deceleration"],
        difficulty="easy",
    ),
    "RANGE_BREAKOUT_positive": ScenarioSpec(
        name="RANGE_BREAKOUT_positive",
        event_type="RANGE_BREAKOUT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 3.5},
        expected_events={"RANGE_BREAKOUT": True},
        excluded_events={},
        tags=["trend", "breakout"],
        difficulty="medium",
    ),
    "RANGE_BREAKOUT_negative": ScenarioSpec(
        name="RANGE_BREAKOUT_negative",
        event_type="RANGE_BREAKOUT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"RANGE_BREAKOUT": False},
        excluded_events={},
        tags=["trend", "breakout"],
        difficulty="easy",
    ),
    "FALSE_BREAKOUT_positive": ScenarioSpec(
        name="FALSE_BREAKOUT_positive",
        event_type="FALSE_BREAKOUT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 4.0},
        expected_events={"FALSE_BREAKOUT": True},
        excluded_events={},
        tags=["trend", "false_breakout"],
        difficulty="hard",
    ),
    "FALSE_BREAKOUT_negative": ScenarioSpec(
        name="FALSE_BREAKOUT_negative",
        event_type="FALSE_BREAKOUT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.0},
        expected_events={"FALSE_BREAKOUT": False},
        excluded_events={},
        tags=["trend", "false_breakout"],
        difficulty="easy",
    ),
    "PULLBACK_PIVOT_positive": ScenarioSpec(
        name="PULLBACK_PIVOT_positive",
        event_type="PULLBACK_PIVOT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.5},
        expected_events={"PULLBACK_PIVOT": True},
        excluded_events={},
        tags=["trend", "pullback"],
        difficulty="medium",
    ),
    "PULLBACK_PIVOT_negative": ScenarioSpec(
        name="PULLBACK_PIVOT_negative",
        event_type="PULLBACK_PIVOT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "down", "magnitude_pct": 2.5},
        expected_events={"PULLBACK_PIVOT": False},
        excluded_events={},
        tags=["trend", "pullback"],
        difficulty="easy",
    ),
    "TREND_EXHAUSTION_TRIGGER_positive": ScenarioSpec(
        name="TREND_EXHAUSTION_TRIGGER_positive",
        event_type="TREND_EXHAUSTION_TRIGGER",
        polarity="positive",
        generator_type="trade_flow",
        injection_method="inject_exhaustion_decay",
        injection_params={"volume_ramp_mult": 4.0, "volume_collapse_pct": 0.75},
        expected_events={"TREND_EXHAUSTION_TRIGGER": True},
        excluded_events={},
        tags=["trend", "exhaustion"],
        difficulty="medium",
    ),
    "TREND_EXHAUSTION_TRIGGER_negative": ScenarioSpec(
        name="TREND_EXHAUSTION_TRIGGER_negative",
        event_type="TREND_EXHAUSTION_TRIGGER",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.5},
        expected_events={"TREND_EXHAUSTION_TRIGGER": False},
        excluded_events={},
        tags=["trend", "exhaustion"],
        difficulty="easy",
    ),
}

__all__ = ["TREND_SCENARIOS"]
