from __future__ import annotations

from ..factory import ScenarioSpec

BASIS_SCENARIOS = {
    "BASIS_DISLOC_positive": ScenarioSpec(
        name="BASIS_DISLOC_positive",
        event_type="BASIS_DISLOC",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 4.0},
        expected_events={"BASIS_DISLOC": True},
        excluded_events={},
        tags=["basis", "dislocation"],
        difficulty="medium",
    ),
    "BASIS_DISLOC_negative": ScenarioSpec(
        name="BASIS_DISLOC_negative",
        event_type="BASIS_DISLOC",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"BASIS_DISLOC": False},
        excluded_events={},
        tags=["basis", "dislocation"],
        difficulty="easy",
    ),
    "CROSS_VENUE_DESYNC_positive": ScenarioSpec(
        name="CROSS_VENUE_DESYNC_positive",
        event_type="CROSS_VENUE_DESYNC",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "down", "magnitude_pct": 3.5},
        expected_events={"CROSS_VENUE_DESYNC": True},
        excluded_events={},
        tags=["basis", "desync"],
        difficulty="hard",
    ),
    "CROSS_VENUE_DESYNC_negative": ScenarioSpec(
        name="CROSS_VENUE_DESYNC_negative",
        event_type="CROSS_VENUE_DESYNC",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.0},
        expected_events={"CROSS_VENUE_DESYNC": False},
        excluded_events={},
        tags=["basis", "desync"],
        difficulty="easy",
    ),
    "FND_DISLOC_positive": ScenarioSpec(
        name="FND_DISLOC_positive",
        event_type="FND_DISLOC",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 4.0},
        expected_events={"FND_DISLOC": True},
        excluded_events={},
        tags=["basis", "funding"],
        difficulty="medium",
    ),
    "FND_DISLOC_negative": ScenarioSpec(
        name="FND_DISLOC_negative",
        event_type="FND_DISLOC",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 0.5},
        expected_events={"FND_DISLOC": False},
        excluded_events={},
        tags=["basis", "funding"],
        difficulty="easy",
    ),
    "SPOT_PERP_BASIS_SHOCK_positive": ScenarioSpec(
        name="SPOT_PERP_BASIS_SHOCK_positive",
        event_type="SPOT_PERP_BASIS_SHOCK",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "down", "magnitude_pct": 3.0},
        expected_events={"SPOT_PERP_BASIS_SHOCK": True},
        excluded_events={},
        tags=["basis", "spot_perp"],
        difficulty="medium",
    ),
    "SPOT_PERP_BASIS_SHOCK_negative": ScenarioSpec(
        name="SPOT_PERP_BASIS_SHOCK_negative",
        event_type="SPOT_PERP_BASIS_SHOCK",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 0.5},
        expected_events={"SPOT_PERP_BASIS_SHOCK": False},
        excluded_events={},
        tags=["basis", "spot_perp"],
        difficulty="easy",
    ),
}

__all__ = ["BASIS_SCENARIOS"]
