from __future__ import annotations

from ..factory import ScenarioSpec

COVERAGE_GAP_SCENARIOS = {
    "ZSCORE_STRETCH_positive": ScenarioSpec(
        name="ZSCORE_STRETCH_positive",
        event_type="ZSCORE_STRETCH",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_zscore_stretch",
        injection_params={"zscore_mult": 4.0},
        expected_events={"ZSCORE_STRETCH": True},
        excluded_events={},
        tags=["statistical", "zscore", "stretch"],
        difficulty="easy",
    ),
    "ZSCORE_STRETCH_negative": ScenarioSpec(
        name="ZSCORE_STRETCH_negative",
        event_type="ZSCORE_STRETCH",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"ZSCORE_STRETCH": False},
        excluded_events={},
        tags=["statistical", "zscore"],
        difficulty="easy",
    ),
    "BAND_BREAK_positive": ScenarioSpec(
        name="BAND_BREAK_positive",
        event_type="BAND_BREAK",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_band_break",
        injection_params={"break_magnitude": 3.5},
        expected_events={"BAND_BREAK": True},
        excluded_events={},
        tags=["statistical", "band", "break"],
        difficulty="medium",
    ),
    "BAND_BREAK_negative": ScenarioSpec(
        name="BAND_BREAK_negative",
        event_type="BAND_BREAK",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"BAND_BREAK": False},
        excluded_events={},
        tags=["statistical", "band"],
        difficulty="easy",
    ),
    "SLIPPAGE_SPIKE_EVENT_positive": ScenarioSpec(
        name="SLIPPAGE_SPIKE_EVENT_positive",
        event_type="SLIPPAGE_SPIKE_EVENT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_slippage_spike",
        injection_params={"slippage_mult": 5.0, "spread_mult": 3.0},
        expected_events={"SLIPPAGE_SPIKE_EVENT": True},
        excluded_events={},
        tags=["execution", "slippage", "friction"],
        difficulty="medium",
    ),
    "SLIPPAGE_SPIKE_EVENT_negative": ScenarioSpec(
        name="SLIPPAGE_SPIKE_EVENT_negative",
        event_type="SLIPPAGE_SPIKE_EVENT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"SLIPPAGE_SPIKE_EVENT": False},
        excluded_events={},
        tags=["execution", "slippage"],
        difficulty="easy",
    ),
    "LIQUIDITY_SHOCK_positive": ScenarioSpec(
        name="LIQUIDITY_SHOCK_positive",
        event_type="LIQUIDITY_SHOCK",
        polarity="positive",
        generator_type="orderbook",
        injection_method="inject_liquidity_shock",
        injection_params={"depth_drop": 0.85, "spread_mult": 4.0},
        expected_events={"LIQUIDITY_SHOCK": True},
        excluded_events={},
        tags=["liquidity", "shock"],
        difficulty="medium",
    ),
    "LIQUIDITY_SHOCK_negative": ScenarioSpec(
        name="LIQUIDITY_SHOCK_negative",
        event_type="LIQUIDITY_SHOCK",
        polarity="negative",
        generator_type="orderbook",
        injection_method="inject_normal_market",
        injection_params={},
        expected_events={"LIQUIDITY_SHOCK": False},
        excluded_events={},
        tags=["liquidity"],
        difficulty="easy",
    ),
    "OI_SPIKE_POSITIVE_positive": ScenarioSpec(
        name="OI_SPIKE_POSITIVE_positive",
        event_type="OI_SPIKE_POSITIVE",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_oi_spike",
        injection_params={"direction": "positive", "spike_mult": 4.0},
        expected_events={"OI_SPIKE_POSITIVE": True},
        excluded_events={},
        tags=["positioning", "open_interest", "spike"],
        difficulty="medium",
    ),
    "OI_SPIKE_POSITIVE_negative": ScenarioSpec(
        name="OI_SPIKE_POSITIVE_negative",
        event_type="OI_SPIKE_POSITIVE",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"OI_SPIKE_POSITIVE": False},
        excluded_events={},
        tags=["positioning", "open_interest"],
        difficulty="easy",
    ),
    "OI_SPIKE_NEGATIVE_positive": ScenarioSpec(
        name="OI_SPIKE_NEGATIVE_positive",
        event_type="OI_SPIKE_NEGATIVE",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_oi_spike",
        injection_params={"direction": "negative", "spike_mult": 4.0},
        expected_events={"OI_SPIKE_NEGATIVE": True},
        excluded_events={},
        tags=["positioning", "open_interest", "spike"],
        difficulty="medium",
    ),
    "OI_SPIKE_NEGATIVE_negative": ScenarioSpec(
        name="OI_SPIKE_NEGATIVE_negative",
        event_type="OI_SPIKE_NEGATIVE",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"OI_SPIKE_NEGATIVE": False},
        excluded_events={},
        tags=["positioning", "open_interest"],
        difficulty="easy",
    ),
    "OI_FLUSH_positive": ScenarioSpec(
        name="OI_FLUSH_positive",
        event_type="OI_FLUSH",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_oi_flush",
        injection_params={"flush_pct": 0.10},
        expected_events={"OI_FLUSH": True},
        excluded_events={},
        tags=["positioning", "open_interest", "flush"],
        difficulty="medium",
    ),
    "OI_FLUSH_negative": ScenarioSpec(
        name="OI_FLUSH_negative",
        event_type="OI_FLUSH",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"OI_FLUSH": False},
        excluded_events={},
        tags=["positioning", "open_interest"],
        difficulty="easy",
    ),
    "LIQUIDATION_CASCADE_positive": ScenarioSpec(
        name="LIQUIDATION_CASCADE_positive",
        event_type="LIQUIDATION_CASCADE",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_liquidation_cascade",
        injection_params={"cascade_depth_pct": 15.0, "volume_mult": 5.0},
        expected_events={"LIQUIDATION_CASCADE": True},
        excluded_events={},
        tags=["liquidation", "cascade", "extreme"],
        difficulty="hard",
    ),
    "LIQUIDATION_CASCADE_negative": ScenarioSpec(
        name="LIQUIDATION_CASCADE_negative",
        event_type="LIQUIDATION_CASCADE",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.0},
        expected_events={"LIQUIDATION_CASCADE": False},
        excluded_events={},
        tags=["liquidation"],
        difficulty="easy",
    ),
    "GAP_OVERSHOOT_positive": ScenarioSpec(
        name="GAP_OVERSHOOT_positive",
        event_type="GAP_OVERSHOOT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_gap_overshoot",
        injection_params={"gap_pct": 3.0, "overshoot_pct": 2.0},
        expected_events={"GAP_OVERSHOOT": True},
        excluded_events={},
        tags=["gap", "overshoot", "price_action"],
        difficulty="medium",
    ),
    "GAP_OVERSHOOT_negative": ScenarioSpec(
        name="GAP_OVERSHOOT_negative",
        event_type="GAP_OVERSHOOT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"GAP_OVERSHOOT": False},
        excluded_events={},
        tags=["gap"],
        difficulty="easy",
    ),
    "OVERSHOOT_AFTER_SHOCK_positive": ScenarioSpec(
        name="OVERSHOOT_AFTER_SHOCK_positive",
        event_type="OVERSHOOT_AFTER_SHOCK",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_overshoot_after_shock",
        injection_params={"shock_pct": 5.0, "overshoot_pct": 2.0},
        expected_events={"OVERSHOOT_AFTER_SHOCK": True},
        excluded_events={},
        tags=["overshoot", "shock", "mean_reversion"],
        difficulty="medium",
    ),
    "OVERSHOOT_AFTER_SHOCK_negative": ScenarioSpec(
        name="OVERSHOOT_AFTER_SHOCK_negative",
        event_type="OVERSHOOT_AFTER_SHOCK",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.0},
        expected_events={"OVERSHOOT_AFTER_SHOCK": False},
        excluded_events={},
        tags=["overshoot"],
        difficulty="easy",
    ),
    "POST_DELEVERAGING_REBOUND_positive": ScenarioSpec(
        name="POST_DELEVERAGING_REBOUND_positive",
        event_type="POST_DELEVERAGING_REBOUND",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_rebound",
        injection_params={"rebound_pct": 8.0, "prior_decline_pct": 20.0},
        expected_events={"POST_DELEVERAGING_REBOUND": True},
        excluded_events={},
        tags=["rebound", "deleveraging", "recovery"],
        difficulty="medium",
    ),
    "POST_DELEVERAGING_REBOUND_negative": ScenarioSpec(
        name="POST_DELEVERAGING_REBOUND_negative",
        event_type="POST_DELEVERAGING_REBOUND",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 2.0},
        expected_events={"POST_DELEVERAGING_REBOUND": False},
        excluded_events={},
        tags=["rebound"],
        difficulty="easy",
    ),
    "SUPPORT_RESISTANCE_BREAK_positive": ScenarioSpec(
        name="SUPPORT_RESISTANCE_BREAK_positive",
        event_type="SUPPORT_RESISTANCE_BREAK",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_sr_break",
        injection_params={"break_pct": 2.0},
        expected_events={"SUPPORT_RESISTANCE_BREAK": True},
        excluded_events={},
        tags=["breakout", "support", "resistance"],
        difficulty="medium",
    ),
    "SUPPORT_RESISTANCE_BREAK_negative": ScenarioSpec(
        name="SUPPORT_RESISTANCE_BREAK_negative",
        event_type="SUPPORT_RESISTANCE_BREAK",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"SUPPORT_RESISTANCE_BREAK": False},
        excluded_events={},
        tags=["support", "resistance"],
        difficulty="easy",
    ),
    "LEAD_LAG_BREAK_positive": ScenarioSpec(
        name="LEAD_LAG_BREAK_positive",
        event_type="LEAD_LAG_BREAK",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_lead_lag_break",
        injection_params={"lag_bps": 50},
        expected_events={"LEAD_LAG_BREAK": True},
        excluded_events={},
        tags=["correlation", "lead_lag", "breakdown"],
        difficulty="hard",
    ),
    "LEAD_LAG_BREAK_negative": ScenarioSpec(
        name="LEAD_LAG_BREAK_negative",
        event_type="LEAD_LAG_BREAK",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"LEAD_LAG_BREAK": False},
        excluded_events={},
        tags=["correlation", "lead_lag"],
        difficulty="easy",
    ),
    "INDEX_COMPONENT_DIVERGENCE_positive": ScenarioSpec(
        name="INDEX_COMPONENT_DIVERGENCE_positive",
        event_type="INDEX_COMPONENT_DIVERGENCE",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_index_divergence",
        injection_params={"divergence_pct": 5.0},
        expected_events={"INDEX_COMPONENT_DIVERGENCE": True},
        excluded_events={},
        tags=["desync", "index", "divergence"],
        difficulty="hard",
    ),
    "INDEX_COMPONENT_DIVERGENCE_negative": ScenarioSpec(
        name="INDEX_COMPONENT_DIVERGENCE_negative",
        event_type="INDEX_COMPONENT_DIVERGENCE",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"INDEX_COMPONENT_DIVERGENCE": False},
        excluded_events={},
        tags=["desync", "index"],
        difficulty="easy",
    ),
    "FEE_REGIME_CHANGE_EVENT_positive": ScenarioSpec(
        name="FEE_REGIME_CHANGE_EVENT_positive",
        event_type="FEE_REGIME_CHANGE_EVENT",
        polarity="positive",
        generator_type="context",
        injection_method="inject_fee_regime_shift",
        injection_params={"target_regime": "high"},
        expected_events={"FEE_REGIME_CHANGE_EVENT": True},
        excluded_events={},
        tags=["funding", "regime", "fee"],
        difficulty="medium",
    ),
    "FEE_REGIME_CHANGE_EVENT_negative": ScenarioSpec(
        name="FEE_REGIME_CHANGE_EVENT_negative",
        event_type="FEE_REGIME_CHANGE_EVENT",
        polarity="negative",
        generator_type="context",
        injection_method="inject_stable_fee",
        injection_params={},
        expected_events={"FEE_REGIME_CHANGE_EVENT": False},
        excluded_events={},
        tags=["funding", "fee"],
        difficulty="easy",
    ),
    "SCHEDULED_NEWS_WINDOW_EVENT_positive": ScenarioSpec(
        name="SCHEDULED_NEWS_WINDOW_EVENT_positive",
        event_type="SCHEDULED_NEWS_WINDOW_EVENT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_news_volatility",
        injection_params={"vol_mult": 3.0},
        expected_events={"SCHEDULED_NEWS_WINDOW_EVENT": True},
        excluded_events={},
        tags=["temporal", "news", "event"],
        difficulty="medium",
    ),
    "SCHEDULED_NEWS_WINDOW_EVENT_negative": ScenarioSpec(
        name="SCHEDULED_NEWS_WINDOW_EVENT_negative",
        event_type="SCHEDULED_NEWS_WINDOW_EVENT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"SCHEDULED_NEWS_WINDOW_EVENT": False},
        excluded_events={},
        tags=["temporal", "news"],
        difficulty="easy",
    ),
    "COPULA_PAIRS_TRADING_positive": ScenarioSpec(
        name="COPULA_PAIRS_TRADING_positive",
        event_type="COPULA_PAIRS_TRADING",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_pairs_divergence",
        injection_params={"spread_zscore": 3.5},
        expected_events={"COPULA_PAIRS_TRADING": True},
        excluded_events={},
        tags=["statistical", "pairs", "copula"],
        difficulty="hard",
    ),
    "COPULA_PAIRS_TRADING_negative": ScenarioSpec(
        name="COPULA_PAIRS_TRADING_negative",
        event_type="COPULA_PAIRS_TRADING",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_stable_market",
        injection_params={},
        expected_events={"COPULA_PAIRS_TRADING": False},
        excluded_events={},
        tags=["statistical", "pairs"],
        difficulty="easy",
    ),
}

__all__ = ["COVERAGE_GAP_SCENARIOS"]
