from __future__ import annotations

from ..factory import ScenarioSpec

LIQUIDITY_SCENARIOS = {
    "LIQUIDITY_VACUUM_positive": ScenarioSpec(
        name="LIQUIDITY_VACUUM_positive",
        event_type="LIQUIDITY_VACUUM",
        polarity="positive",
        generator_type="orderbook",
        injection_method="inject_liquidity_vacuum",
        injection_params={"depth_drop": 0.75, "spread_mult": 4.0},
        expected_events={"LIQUIDITY_VACUUM": True},
        excluded_events={"LIQUIDITY_STRESS_PROXY": True},
        tags=["liquidity", "vacuum"],
        difficulty="easy",
    ),
    "LIQUIDITY_VACUUM_negative": ScenarioSpec(
        name="LIQUIDITY_VACUUM_negative",
        event_type="LIQUIDITY_VACUUM",
        polarity="negative",
        generator_type="orderbook",
        injection_method="inject_normal_market",
        injection_params={},
        expected_events={"LIQUIDITY_VACUUM": False},
        excluded_events={},
        tags=["liquidity", "vacuum"],
        difficulty="easy",
    ),
    "LIQUIDITY_STRESS_PROXY_positive": ScenarioSpec(
        name="LIQUIDITY_STRESS_PROXY_positive",
        event_type="LIQUIDITY_STRESS_PROXY",
        polarity="positive",
        generator_type="orderbook",
        injection_method="inject_liquidity_vacuum",
        injection_params={"depth_drop": 0.60, "spread_mult": 3.5},
        expected_events={"LIQUIDITY_STRESS_PROXY": True},
        excluded_events={},
        tags=["liquidity", "stress"],
        difficulty="easy",
    ),
    "LIQUIDITY_STRESS_PROXY_negative": ScenarioSpec(
        name="LIQUIDITY_STRESS_PROXY_negative",
        event_type="LIQUIDITY_STRESS_PROXY",
        polarity="negative",
        generator_type="orderbook",
        injection_method="inject_normal_market",
        injection_params={},
        expected_events={"LIQUIDITY_STRESS_PROXY": False},
        excluded_events={},
        tags=["liquidity", "stress"],
        difficulty="easy",
    ),
    "LIQUIDITY_STRESS_DIRECT_positive": ScenarioSpec(
        name="LIQUIDITY_STRESS_DIRECT_positive",
        event_type="LIQUIDITY_STRESS_DIRECT",
        polarity="positive",
        generator_type="orderbook",
        injection_method="inject_liquidity_vacuum",
        injection_params={"depth_drop": 0.65, "spread_mult": 3.0},
        expected_events={"LIQUIDITY_STRESS_DIRECT": True},
        excluded_events={},
        tags=["liquidity", "stress", "direct"],
        difficulty="medium",
    ),
    "LIQUIDITY_STRESS_DIRECT_negative": ScenarioSpec(
        name="LIQUIDITY_STRESS_DIRECT_negative",
        event_type="LIQUIDITY_STRESS_DIRECT",
        polarity="negative",
        generator_type="orderbook",
        injection_method="inject_normal_market",
        injection_params={},
        expected_events={"LIQUIDITY_STRESS_DIRECT": False},
        excluded_events={},
        tags=["liquidity", "stress", "direct"],
        difficulty="easy",
    ),
    "DEPTH_COLLAPSE_positive": ScenarioSpec(
        name="DEPTH_COLLAPSE_positive",
        event_type="DEPTH_COLLAPSE",
        polarity="positive",
        generator_type="orderbook",
        injection_method="inject_spoofing_walls",
        injection_params={"depth_drop": 0.70},
        expected_events={"DEPTH_COLLAPSE": True},
        excluded_events={},
        tags=["liquidity", "depth"],
        difficulty="medium",
    ),
    "DEPTH_COLLAPSE_negative": ScenarioSpec(
        name="DEPTH_COLLAPSE_negative",
        event_type="DEPTH_COLLAPSE",
        polarity="negative",
        generator_type="orderbook",
        injection_method="inject_normal_market",
        injection_params={},
        expected_events={"DEPTH_COLLAPSE": False},
        excluded_events={},
        tags=["liquidity", "depth"],
        difficulty="easy",
    ),
    "SPREAD_BLOWOUT_positive": ScenarioSpec(
        name="SPREAD_BLOWOUT_positive",
        event_type="SPREAD_BLOWOUT",
        polarity="positive",
        generator_type="orderbook",
        injection_method="inject_liquidity_vacuum",
        injection_params={"depth_drop": 0.50, "spread_mult": 5.0},
        expected_events={"SPREAD_BLOWOUT": True},
        excluded_events={},
        tags=["liquidity", "spread"],
        difficulty="easy",
    ),
    "SPREAD_BLOWOUT_negative": ScenarioSpec(
        name="SPREAD_BLOWOUT_negative",
        event_type="SPREAD_BLOWOUT",
        polarity="negative",
        generator_type="orderbook",
        injection_method="inject_normal_market",
        injection_params={},
        expected_events={"SPREAD_BLOWOUT": False},
        excluded_events={},
        tags=["liquidity", "spread"],
        difficulty="easy",
    ),
    "ABSORPTION_EVENT_positive": ScenarioSpec(
        name="ABSORPTION_EVENT_positive",
        event_type="ABSORPTION_EVENT",
        polarity="positive",
        generator_type="orderbook",
        injection_method="inject_liquidity_vacuum",
        injection_params={"depth_drop": 0.55, "spread_mult": 3.5},
        expected_events={"ABSORPTION_EVENT": True},
        excluded_events={},
        tags=["liquidity", "absorption"],
        difficulty="medium",
    ),
    "ABSORPTION_EVENT_negative": ScenarioSpec(
        name="ABSORPTION_EVENT_negative",
        event_type="ABSORPTION_EVENT",
        polarity="negative",
        generator_type="orderbook",
        injection_method="inject_normal_market",
        injection_params={},
        expected_events={"ABSORPTION_EVENT": False},
        excluded_events={},
        tags=["liquidity", "absorption"],
        difficulty="easy",
    ),
    "SWEEP_STOPRUN_positive": ScenarioSpec(
        name="SWEEP_STOPRUN_positive",
        event_type="SWEEP_STOPRUN",
        polarity="positive",
        generator_type="trade_flow",
        injection_method="inject_aggressive_burst",
        injection_params={"volume_mult": 5.0, "price_move_pct": 2.5},
        expected_events={"SWEEP_STOPRUN": True},
        excluded_events={},
        tags=["liquidity", "stoprun"],
        difficulty="medium",
    ),
    "SWEEP_STOPRUN_negative": ScenarioSpec(
        name="SWEEP_STOPRUN_negative",
        event_type="SWEEP_STOPRUN",
        polarity="negative",
        generator_type="trade_flow",
        injection_method="inject_steady_flow",
        injection_params={},
        expected_events={"SWEEP_STOPRUN": False},
        excluded_events={},
        tags=["liquidity", "stoprun"],
        difficulty="easy",
    ),
    "LIQUIDITY_GAP_PRINT_positive": ScenarioSpec(
        name="LIQUIDITY_GAP_PRINT_positive",
        event_type="LIQUIDITY_GAP_PRINT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 6.0, "wick_mult": 4.0},
        expected_events={"LIQUIDITY_GAP_PRINT": True},
        excluded_events={},
        tags=["liquidity", "gap"],
        difficulty="medium",
    ),
    "LIQUIDITY_GAP_PRINT_negative": ScenarioSpec(
        name="LIQUIDITY_GAP_PRINT_negative",
        event_type="LIQUIDITY_GAP_PRINT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.0},
        expected_events={"LIQUIDITY_GAP_PRINT": False},
        excluded_events={},
        tags=["liquidity", "gap"],
        difficulty="easy",
    ),
}

__all__ = ["LIQUIDITY_SCENARIOS"]
