from __future__ import annotations

from ..factory import ScenarioSpec

ORDERFLOW_SCENARIOS = {
    "ORDERFLOW_IMBALANCE_SHOCK_positive": ScenarioSpec(
        name="ORDERFLOW_IMBALANCE_SHOCK_positive",
        event_type="ORDERFLOW_IMBALANCE_SHOCK",
        polarity="positive",
        generator_type="trade_flow",
        injection_method="inject_exhaustion_decay",
        injection_params={"volume_ramp_mult": 4.0, "volume_collapse_pct": 0.80, "rv_increase": 3.0},
        expected_events={"ORDERFLOW_IMBALANCE_SHOCK": True},
        excluded_events={},
        tags=["orderflow", "imbalance"],
        difficulty="medium",
    ),
    "ORDERFLOW_IMBALANCE_SHOCK_negative": ScenarioSpec(
        name="ORDERFLOW_IMBALANCE_SHOCK_negative",
        event_type="ORDERFLOW_IMBALANCE_SHOCK",
        polarity="negative",
        generator_type="trade_flow",
        injection_method="inject_steady_flow",
        injection_params={},
        expected_events={"ORDERFLOW_IMBALANCE_SHOCK": False},
        excluded_events={},
        tags=["orderflow", "imbalance"],
        difficulty="easy",
    ),
    "FLOW_EXHAUSTION_PROXY_positive": ScenarioSpec(
        name="FLOW_EXHAUSTION_PROXY_positive",
        event_type="FLOW_EXHAUSTION_PROXY",
        polarity="positive",
        generator_type="trade_flow",
        injection_method="inject_exhaustion_decay",
        injection_params={"volume_ramp_mult": 5.0, "volume_collapse_pct": 0.85, "rv_increase": 4.0},
        expected_events={"FLOW_EXHAUSTION_PROXY": True},
        excluded_events={},
        tags=["orderflow", "exhaustion"],
        difficulty="medium",
    ),
    "FLOW_EXHAUSTION_PROXY_negative": ScenarioSpec(
        name="FLOW_EXHAUSTION_PROXY_negative",
        event_type="FLOW_EXHAUSTION_PROXY",
        polarity="negative",
        generator_type="trade_flow",
        injection_method="inject_steady_flow",
        injection_params={},
        expected_events={"FLOW_EXHAUSTION_PROXY": False},
        excluded_events={},
        tags=["orderflow", "exhaustion"],
        difficulty="easy",
    ),
    "FORCED_FLOW_EXHAUSTION_positive": ScenarioSpec(
        name="FORCED_FLOW_EXHAUSTION_positive",
        event_type="FORCED_FLOW_EXHAUSTION",
        polarity="positive",
        generator_type="trade_flow",
        injection_method="inject_exhaustion_decay",
        injection_params={"volume_ramp_mult": 6.0, "volume_collapse_pct": 0.90, "rv_increase": 5.0},
        expected_events={"FORCED_FLOW_EXHAUSTION": True},
        excluded_events={},
        tags=["orderflow", "exhaustion"],
        difficulty="hard",
    ),
    "FORCED_FLOW_EXHAUSTION_negative": ScenarioSpec(
        name="FORCED_FLOW_EXHAUSTION_negative",
        event_type="FORCED_FLOW_EXHAUSTION",
        polarity="negative",
        generator_type="trade_flow",
        injection_method="inject_steady_flow",
        injection_params={},
        expected_events={"FORCED_FLOW_EXHAUSTION": False},
        excluded_events={},
        tags=["orderflow", "exhaustion"],
        difficulty="easy",
    ),
    "CLIMAX_VOLUME_BAR_positive": ScenarioSpec(
        name="CLIMAX_VOLUME_BAR_positive",
        event_type="CLIMAX_VOLUME_BAR",
        polarity="positive",
        generator_type="trade_flow",
        injection_method="inject_aggressive_burst",
        injection_params={"volume_mult": 8.0, "price_move_pct": 3.0},
        expected_events={"CLIMAX_VOLUME_BAR": True},
        excluded_events={},
        tags=["orderflow", "climax"],
        difficulty="medium",
    ),
    "CLIMAX_VOLUME_BAR_negative": ScenarioSpec(
        name="CLIMAX_VOLUME_BAR_negative",
        event_type="CLIMAX_VOLUME_BAR",
        polarity="negative",
        generator_type="trade_flow",
        injection_method="inject_steady_flow",
        injection_params={},
        expected_events={"CLIMAX_VOLUME_BAR": False},
        excluded_events={},
        tags=["orderflow", "climax"],
        difficulty="easy",
    ),
    "WICK_REVERSAL_PROXY_positive": ScenarioSpec(
        name="WICK_REVERSAL_PROXY_positive",
        event_type="WICK_REVERSAL_PROXY",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 4.0, "wick_mult": 3.0},
        expected_events={"WICK_REVERSAL_PROXY": True},
        excluded_events={},
        tags=["orderflow", "wick_reversal"],
        difficulty="medium",
    ),
    "WICK_REVERSAL_PROXY_negative": ScenarioSpec(
        name="WICK_REVERSAL_PROXY_negative",
        event_type="WICK_REVERSAL_PROXY",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.0},
        expected_events={"WICK_REVERSAL_PROXY": False},
        excluded_events={},
        tags=["orderflow", "wick_reversal"],
        difficulty="easy",
    ),
}

__all__ = ["ORDERFLOW_SCENARIOS"]
