from __future__ import annotations

from ..factory import ScenarioSpec

TEMPORAL_SCENARIOS = {
    "SESSION_OPEN_EVENT_positive": ScenarioSpec(
        name="SESSION_OPEN_EVENT_positive",
        event_type="SESSION_OPEN_EVENT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 3.0},
        n_bars=200,
        injection_point=9,
        injection_duration=3,
        expected_events={"SESSION_OPEN_EVENT": True},
        excluded_events={},
        tags=["temporal", "session"],
        difficulty="easy",
    ),
    "SESSION_OPEN_EVENT_negative": ScenarioSpec(
        name="SESSION_OPEN_EVENT_negative",
        event_type="SESSION_OPEN_EVENT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 0.5},
        n_bars=200,
        injection_point=50,
        injection_duration=5,
        expected_events={"SESSION_OPEN_EVENT": False},
        excluded_events={},
        tags=["temporal", "session"],
        difficulty="easy",
    ),
    "SESSION_CLOSE_EVENT_positive": ScenarioSpec(
        name="SESSION_CLOSE_EVENT_positive",
        event_type="SESSION_CLOSE_EVENT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 3.0},
        n_bars=200,
        injection_point=189,
        injection_duration=3,
        expected_events={"SESSION_CLOSE_EVENT": True},
        excluded_events={},
        tags=["temporal", "session"],
        difficulty="easy",
    ),
    "SESSION_CLOSE_EVENT_negative": ScenarioSpec(
        name="SESSION_CLOSE_EVENT_negative",
        event_type="SESSION_CLOSE_EVENT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 0.5},
        n_bars=200,
        injection_point=50,
        injection_duration=5,
        expected_events={"SESSION_CLOSE_EVENT": False},
        excluded_events={},
        tags=["temporal", "session"],
        difficulty="easy",
    ),
    "FUNDING_TIMESTAMP_EVENT_positive": ScenarioSpec(
        name="FUNDING_TIMESTAMP_EVENT_positive",
        event_type="FUNDING_TIMESTAMP_EVENT",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.5},
        n_bars=300,
        injection_point=144,
        injection_duration=5,
        expected_events={"FUNDING_TIMESTAMP_EVENT": True},
        excluded_events={},
        tags=["temporal", "funding"],
        difficulty="easy",
    ),
    "FUNDING_TIMESTAMP_EVENT_negative": ScenarioSpec(
        name="FUNDING_TIMESTAMP_EVENT_negative",
        event_type="FUNDING_TIMESTAMP_EVENT",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 0.5},
        n_bars=300,
        injection_point=50,
        injection_duration=5,
        expected_events={"FUNDING_TIMESTAMP_EVENT": False},
        excluded_events={},
        tags=["temporal", "funding"],
        difficulty="easy",
    ),
}

__all__ = ["TEMPORAL_SCENARIOS"]
