from __future__ import annotations

from ..factory import ScenarioSpec

VOLATILITY_SCENARIOS = {
    "VOL_SPIKE_positive": ScenarioSpec(
        name="VOL_SPIKE_positive",
        event_type="VOL_SPIKE",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 5.0, "wick_mult": 4.0},
        expected_events={"VOL_SPIKE": True},
        excluded_events={},
        tags=["volatility", "spike"],
        difficulty="easy",
    ),
    "VOL_SPIKE_negative": ScenarioSpec(
        name="VOL_SPIKE_negative",
        event_type="VOL_SPIKE",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.0},
        expected_events={"VOL_SPIKE": False},
        excluded_events={},
        tags=["volatility", "spike"],
        difficulty="easy",
    ),
    "VOL_RELAXATION_START_positive": ScenarioSpec(
        name="VOL_RELAXATION_START_positive",
        event_type="VOL_RELAXATION_START",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.5, "frequency": 15},
        expected_events={"VOL_RELAXATION_START": True},
        excluded_events={},
        tags=["volatility", "relaxation"],
        difficulty="medium",
    ),
    "VOL_RELAXATION_START_negative": ScenarioSpec(
        name="VOL_RELAXATION_START_negative",
        event_type="VOL_RELAXATION_START",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 5.0},
        expected_events={"VOL_RELAXATION_START": False},
        excluded_events={},
        tags=["volatility", "relaxation"],
        difficulty="easy",
    ),
    "VOL_CLUSTER_SHIFT_positive": ScenarioSpec(
        name="VOL_CLUSTER_SHIFT_positive",
        event_type="VOL_CLUSTER_SHIFT",
        polarity="positive",
        generator_type="context",
        injection_method="inject_vol_regime_shift",
        injection_params={"target_regime": "high"},
        expected_events={"VOL_CLUSTER_SHIFT": True},
        excluded_events={},
        tags=["volatility", "regime"],
        difficulty="medium",
    ),
    "VOL_CLUSTER_SHIFT_negative": ScenarioSpec(
        name="VOL_CLUSTER_SHIFT_negative",
        event_type="VOL_CLUSTER_SHIFT",
        polarity="negative",
        generator_type="context",
        injection_method="inject_vol_regime_shift",
        injection_params={"target_regime": "mid"},
        expected_events={"VOL_CLUSTER_SHIFT": False},
        excluded_events={},
        tags=["volatility", "regime"],
        difficulty="easy",
    ),
    "RANGE_COMPRESSION_END_positive": ScenarioSpec(
        name="RANGE_COMPRESSION_END_positive",
        event_type="RANGE_COMPRESSION_END",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 4.0},
        expected_events={"RANGE_COMPRESSION_END": True},
        excluded_events={},
        tags=["volatility", "compression"],
        difficulty="medium",
    ),
    "RANGE_COMPRESSION_END_negative": ScenarioSpec(
        name="RANGE_COMPRESSION_END_negative",
        event_type="RANGE_COMPRESSION_END",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"RANGE_COMPRESSION_END": False},
        excluded_events={},
        tags=["volatility", "compression"],
        difficulty="easy",
    ),
    "BREAKOUT_TRIGGER_positive": ScenarioSpec(
        name="BREAKOUT_TRIGGER_positive",
        event_type="BREAKOUT_TRIGGER",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 3.0},
        expected_events={"BREAKOUT_TRIGGER": True},
        excluded_events={},
        tags=["volatility", "breakout"],
        difficulty="medium",
    ),
    "BREAKOUT_TRIGGER_negative": ScenarioSpec(
        name="BREAKOUT_TRIGGER_negative",
        event_type="BREAKOUT_TRIGGER",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_mean_reverting",
        injection_params={"oscillation_pct": 1.0},
        expected_events={"BREAKOUT_TRIGGER": False},
        excluded_events={},
        tags=["volatility", "breakout"],
        difficulty="easy",
    ),
    "VOL_SHOCK_positive": ScenarioSpec(
        name="VOL_SHOCK_positive",
        event_type="VOL_SHOCK",
        polarity="positive",
        generator_type="price_series",
        injection_method="inject_volatility_spike",
        injection_params={"vol_mult": 8.0, "wick_mult": 5.0},
        expected_events={"VOL_SHOCK": True},
        excluded_events={},
        tags=["volatility", "shock"],
        difficulty="hard",
    ),
    "VOL_SHOCK_negative": ScenarioSpec(
        name="VOL_SHOCK_negative",
        event_type="VOL_SHOCK",
        polarity="negative",
        generator_type="price_series",
        injection_method="inject_trending",
        injection_params={"direction": "up", "magnitude_pct": 1.0},
        expected_events={"VOL_SHOCK": False},
        excluded_events={},
        tags=["volatility", "shock"],
        difficulty="easy",
    ),
}

__all__ = ["VOLATILITY_SCENARIOS"]
