from .liquidity import LIQUIDITY_SCENARIOS
from .orderflow import ORDERFLOW_SCENARIOS
from .volatility import VOLATILITY_SCENARIOS
from .basis import BASIS_SCENARIOS
from .funding import FUNDING_SCENARIOS
from .trend import TREND_SCENARIOS
from .regime import REGIME_SCENARIOS
from .temporal import TEMPORAL_SCENARIOS
from .coverage_gaps import COVERAGE_GAP_SCENARIOS

ALL_SCENARIOS = {}
for module in [LIQUIDITY_SCENARIOS, ORDERFLOW_SCENARIOS, VOLATILITY_SCENARIOS,
               BASIS_SCENARIOS, FUNDING_SCENARIOS, TREND_SCENARIOS,
               REGIME_SCENARIOS, TEMPORAL_SCENARIOS, COVERAGE_GAP_SCENARIOS]:
    if module:
        ALL_SCENARIOS.update(module)

__all__ = [
    "LIQUIDITY_SCENARIOS",
    "ORDERFLOW_SCENARIOS",
    "VOLATILITY_SCENARIOS",
    "BASIS_SCENARIOS",
    "FUNDING_SCENARIOS",
    "TREND_SCENARIOS",
    "REGIME_SCENARIOS",
    "TEMPORAL_SCENARIOS",
    "COVERAGE_GAP_SCENARIOS",
    "ALL_SCENARIOS",
]
