"""Artifact path and payload helpers for run- and report-scoped outputs."""

from project.artifacts.catalog import (
    blueprint_dir,
    blueprint_summary_path,
    checklist_path,
    data_root,
    kpi_scorecard_path,
    live_thesis_dir,
    live_thesis_index_path,
    live_thesis_root,
    load_json_dict,
    phase2_candidates_path,
    phase2_diagnostics_path,
    promoted_theses_path,
    promoted_blueprints_path,
    promotion_dir,
    promotion_report_path,
    promotion_summary_path,
    release_signoff_path,
    reports_dir,
    research_checklist_dir,
    run_dir,
    run_manifest_path,
)

__all__ = [
    "blueprint_dir",
    "blueprint_summary_path",
    "checklist_path",
    "data_root",
    "kpi_scorecard_path",
    "live_thesis_dir",
    "live_thesis_index_path",
    "live_thesis_root",
    "load_json_dict",
    "phase2_candidates_path",
    "phase2_diagnostics_path",
    "promoted_theses_path",
    "promoted_blueprints_path",
    "promotion_dir",
    "promotion_report_path",
    "promotion_summary_path",
    "release_signoff_path",
    "reports_dir",
    "research_checklist_dir",
    "run_dir",
    "run_manifest_path",
]
